commit

diff --git a/.github/workflows/user-java-ci.yml b/.github/workflows/user-java-ci.yml
--- a/.github/workflows/user-java-ci.yml
+++ b/.github/workflows/user-java-ci.yml
@@ -17,8 +17,6 @@ on:
       - 'apis/user-java/**'
       # - ${{ env.MAVEN_HOME }}/**
 
-permissions:
-  issues: write
 
 jobs:
   build:
@@ -29,40 +27,53 @@ jobs:
     permissions:
       contents: read
       packages: write
+      issues: write
 
     steps:
     - uses: actions/checkout@v2
-    
-    - name: Print the input name to STDOUT
-      run: echo First Test
 
-    # - name: Set up JDK 11
-    #   uses: actions/setup-java@v2
-    #   with:
-    #     java-version: '11'
-    #     distribution: 'adopt'
-    #     server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
-    #     settings-path: ${{ github.workspace }} # location for the settings.xml file
-
-    # - name: Build with Maven
-    #   working-directory: ${{ env.MAVEN_HOME }}
-    #   run: mvn clean install
-
-    # - name: Test Maven
-    #   working-directory: ${{ env.MAVEN_HOME }}
-    #   run: mvn test
-      
-    - name: Step To cause error
-      run:  exit 1
-
-    - name: create issue manually
-      if: ${{ failure() }}
+    - name: Create issue using REST API
       run: |
-          curl --request POST \
-          --url https://api.github.com/repos/${{ github.repository }}/issues \
-          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-          --header 'content-type: application/json' \
-          --data '{
-            "title": "Issue created due to workflow fialure: ${{ github.run_id }}",
-            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: _${{ github.run_id }}_."
-            }'
+        curl --request POST \
+        --url https://api.github.com/repos/${{ github.repository }}/issues \
+        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+        --header 'content-type: application/json' \
+        --data '{
+          "title": "Automated issue for commit: ${{ github.sha }}",
+          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
+          }' \
+        --fail
+    
+    # - name: Print the input name to STDOUT
+    #   run: echo First Test
+
+    # # - name: Set up JDK 11
+    # #   uses: actions/setup-java@v2
+    # #   with:
+    # #     java-version: '11'
+    # #     distribution: 'adopt'
+    # #     server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
+    # #     settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+    # # - name: Build with Maven
+    # #   working-directory: ${{ env.MAVEN_HOME }}
+    # #   run: mvn clean install
+
+    # # - name: Test Maven
+    # #   working-directory: ${{ env.MAVEN_HOME }}
+    # #   run: mvn test
+      
+    # - name: Step To cause error
+    #   run:  exit 1
+
+    # - name: create issue manually
+    #   if: ${{ failure() }}
+    #   run: |
+    #       curl --request POST \
+    #       --url https://api.github.com/repos/${{ github.repository }}/issues \
+    #       --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+    #       --header 'content-type: application/json' \
+    #       --data '{
+    #         "title": "Issue created due to workflow fialure: ${{ github.run_id }}",
+    #         "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: _${{ github.run_id }}_."
+    #         }'
